# -*- coding: utf-8 -*-
"""DL_hand-in 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N39hRSO9HxHVway9DoAaNQbQ6VGMp7Xr
"""

!unzip MNIST.zip

import time  # For measuring elapsed time
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix  # For later exercises, but included here

# Import from utils.py (upload utils.py to Colab first)
from utils import load_mnist, training_curve_plot

# Set device for GPU acceleration (Colab T4)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# Step 1: Load MNIST data (using utils.py function)
# What this does: Loads flattened (784-dim) images and one-hot labels as NumPy arrays.
# We convert to PyTorch tensors and create DataLoaders for mini-batching.
X_train, Y_train, X_test, Y_test = load_mnist()
train_dataset = TensorDataset(torch.tensor(X_train, dtype=torch.float32), torch.tensor(np.argmax(Y_train, axis=1), dtype=torch.long))
test_dataset = TensorDataset(torch.tensor(X_test, dtype=torch.float32), torch.tensor(np.argmax(Y_test, axis=1), dtype=torch.long))

batch_size = 128  # From Assignment 1
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

# Step 2: Define the FC network (same as Assignment 1: [784, 128, 64, 10] with ReLU)
# What this does: nn.Sequential stacks layers. nn.Linear is like your matrix multiply + bias.
# ReLU between hidden layers. Output is logits (no softmax—loss handles it).
class FCNet(nn.Module):
    def __init__(self):
        super(FCNet, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(784, 128),  # Input to hidden1
            nn.ReLU(),
            nn.Linear(128, 64),   # Hidden1 to hidden2
            nn.ReLU(),
            nn.Linear(64, 10)     # Hidden2 to output (logits for 10 classes)
        )

    def forward(self, x):
        return self.net(x)

model = FCNet().to(device)  # Move to GPU

# Step 3: Loss and optimizer
# What this does: CrossEntropyLoss computes Eq. 2 (cross-entropy on logits, averaged over batch).
# SGD optimizer (plain, no momentum for simplicity; matches Assignment 1's mini-batch GD).
criterion = nn.CrossEntropyLoss()
learning_rate = 0.01  # From Assignment 1 ReLU net
optimizer = optim.SGD(model.parameters(), lr=learning_rate)

# Step 4: Training loop (as per instructions)
# What this does: Loops over epochs. For each epoch:
# - Train: Process batches, compute loss/acc per batch, update weights, collect for epoch avg.
# - Test: Evaluate full test set for epoch cost/acc.
# Collects lists for plotting. Measures total time.
num_epochs = 50  # From Assignment 1
train_costs = []
test_costs = []
train_accuracy = []
test_accuracy = []

start_time = time.time()  # Start timer

for epoch in range(num_epochs):
    model.train()  # Training mode
    batch_losses = []
    batch_accs = []

    for batch_x, batch_y in train_loader:
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)

        optimizer.zero_grad()  # Clear gradients
        outputs = model(batch_x)  # Forward pass
        loss = criterion(outputs, batch_y)  # Compute loss (Eq. 2 avg over batch)
        loss.backward()  # Backprop
        optimizer.step()  # Update weights

        batch_losses.append(loss.item())  # Collect batch cost

        # Batch accuracy: argmax on logits == true labels
        _, preds = torch.max(outputs, 1)
        acc = (preds == batch_y).float().mean().item()
        batch_accs.append(acc)

    # Epoch train avg
    train_costs.append(np.mean(batch_losses))
    train_accuracy.append(np.mean(batch_accs))

    # Test evaluation
    model.eval()  # Eval mode (no dropout/BN changes here yet)
    test_loss = 0
    test_correct = 0
    with torch.no_grad():
        for test_x, test_y in test_loader:
            test_x, test_y = test_x.to(device), test_y.to(device)
            outputs = model(test_x)
            loss = criterion(outputs, test_y)
            test_loss += loss.item() * test_x.size(0)  # Sum losses (weighted by batch size)
            _, preds = torch.max(outputs, 1)
            test_correct += (preds == test_y).sum().item()

    test_costs.append(test_loss / len(test_dataset))  # Avg test cost
    test_accuracy.append(test_correct / len(test_dataset))  # Test acc

    print(f"Epoch {epoch+1}/{num_epochs}: Train Cost {train_costs[-1]:.4f}, Train Acc {train_accuracy[-1]:.4f}, Test Cost {test_costs[-1]:.4f}, Test Acc {test_accuracy[-1]:.4f}")

elapsed = time.time() - start_time  # End timer
print(f"Training completed in {elapsed:.2f} seconds")

# Step 5: Plot learning curves (using utils.py function)
# What this does: Calls the provided plot function with the lists and params.
# Shows costs/accs vs. epochs, with final values in legends.
training_curve_plot(
    title="FC Net with ReLU (PyTorch) on MNIST",
    train_costs=train_costs,
    test_costs=test_costs,
    train_accuracy=train_accuracy,
    test_accuracy=test_accuracy,
    batch_size=batch_size,
    learning_rate=learning_rate,
    num_epochs=num_epochs,
    elapsed=elapsed
)
#plt.savefig("FC_net_wReLU_learning_curves_lr0.01.png", dpi=150, bbox_inches="tight")

"""**EXERCISE-2**"""

# Reshape data for CNN: [N, 784] → [N, 1, 28, 28]
# In load_mnist, X_train/X_test are (N, 784); reshape them
X_train_cnn = X_train.reshape(-1, 1, 28, 28)
X_test_cnn  = X_test.reshape(-1, 1, 28, 28)

train_dataset_cnn = TensorDataset(torch.tensor(X_train_cnn, dtype=torch.float32),
                                  torch.tensor(np.argmax(Y_train, axis=1), dtype=torch.long))
test_dataset_cnn  = TensorDataset(torch.tensor(X_test_cnn, dtype=torch.float32),
                                  torch.tensor(np.argmax(Y_test, axis=1), dtype=torch.long))

train_loader_cnn = DataLoader(train_dataset_cnn, batch_size=128, shuffle=True)
test_loader_cnn  = DataLoader(test_dataset_cnn, batch_size=128, shuffle=False)

import torch
import torch.nn as nn
import torch.nn.functional as F   # for functional relu / max_pool2d

class ExactMNISTCNN(nn.Module):
    def __init__(self):
        super(ExactMNISTCNN, self).__init__()

        # 1. Conv: 8 × 3×3×1, stride=1, padding=1
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=8, kernel_size=3, stride=1, padding=1)

        # 4. Conv: 16 × 3×3×8
        self.conv2 = nn.Conv2d(in_channels=8, out_channels=16, kernel_size=3, stride=1, padding=1)

        # 7. Conv: 32 × 3×3×16
        self.conv3 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, stride=1, padding=1)

        # 10. FC to 10 outputs (logits)
        # After conv3 + ReLU: 32 × 7 × 7 = 1568 features
        self.fc = nn.Linear(32 * 7 * 7, 10)

    def forward(self, x):
        # Conv1 → ReLU → MaxPool
        x = self.conv1(x)           # → 8×28×28
        x = F.relu(x)
        x = F.max_pool2d(x, kernel_size=2, stride=2)   # → 8×14×14

        # Conv2 → ReLU → MaxPool
        x = self.conv2(x)           # → 16×14×14
        x = F.relu(x)
        x = F.max_pool2d(x, kernel_size=2, stride=2)   # → 16×7×7

        # Conv3 → ReLU (no pooling after this one)
        x = self.conv3(x)           # → 32×7×7
        x = F.relu(x)

        # Flatten
        x = x.view(x.size(0), -1)   # → batch × 1568

        # FC to 10 logits
        x = self.fc(x)
        return x

# Instantiate and move to device (same as before)
model_cnn = ExactMNISTCNN().to(device)

print(model_cnn)  # inspect the structure

def print_model_parameters(model):
    print("Layer-by-layer trainable parameter counts:\n")
    total_params = 0

    for name, param in model.named_parameters():
        if param.requires_grad:  # only trainable params
            num_params = param.numel()  # total elements in this tensor
            print(f"{name:25s}: {num_params:8,} parameters")
            total_params += num_params

    print(f"\nTotal trainable parameters: {total_params:,}")
    print(f"(This matches the exact specification: ~21,578 params)")

# Call it
print_model_parameters(model_cnn)

# Loss & Optimizer (start with same lr=0.003 or try 0.01)
criterion = nn.CrossEntropyLoss()
learning_rate = 0.01
optimizer = optim.SGD(model_cnn.parameters(), lr=learning_rate)  # added momemtum=0.9  ## or Adam for faster convergence: optim.Adam(..., lr=0.001)

# Loss & Optimizer (start with same lr=0.003 or try 0.01)
#------------------------------------ADAM----------------------------------------EXERCISE-4---------------------------------------------
criterion = nn.CrossEntropyLoss()
learning_rate = 0.01
optimizer = optim.Adam(params=model_cnn.parameters())  # added momemtum  ## or Adam for faster convergence: optim.Adam(..., lr=0.001)

num_epochs = 50  # From Assignment 1
train_costs = []
test_costs = []
train_accuracy = []
test_accuracy = []

start_time = time.time()  # Start timer

for epoch in range(num_epochs):
    model_cnn.train()  # Training mode
    batch_losses = []
    batch_accs = []

    for batch_x, batch_y in train_loader_cnn:
        batch_x, batch_y = batch_x.to(device), batch_y.to(device)

        optimizer.zero_grad()  # Clear gradients
        outputs = model_cnn(batch_x)  # Forward pass
        loss = criterion(outputs, batch_y)  # Compute loss (Eq. 2 avg over batch)
        loss.backward()  # Backprop
        optimizer.step()  # Update weights

        batch_losses.append(loss.item())  # Collect batch cost

        # Batch accuracy: argmax on logits == true labels
        _, preds = torch.max(outputs, 1)
        acc = (preds == batch_y).float().mean().item()
        batch_accs.append(acc)

    # Epoch train avg
    train_costs.append(np.mean(batch_losses))
    train_accuracy.append(np.mean(batch_accs))

    # Test evaluation
    model_cnn.eval()  # Eval mode (no dropout/BN changes here yet)
    test_loss = 0
    test_correct = 0
    with torch.no_grad():
        for test_x, test_y in test_loader_cnn:
            test_x, test_y = test_x.to(device), test_y.to(device)
            outputs = model_cnn(test_x)
            loss = criterion(outputs, test_y)
            test_loss += loss.item() * test_x.size(0)  # Sum losses (weighted by batch size)
            _, preds = torch.max(outputs, 1)
            test_correct += (preds == test_y).sum().item()

    test_costs.append(test_loss / len(test_loader_cnn.dataset))  # Avg test cost
    test_accuracy.append(test_correct / len(test_loader_cnn.dataset))  # Test acc

    print(f"Epoch {epoch+1}/{num_epochs}: Train Cost {train_costs[-1]:.4f}, Train Acc {train_accuracy[-1]:.4f}, Test Cost {test_costs[-1]:.4f}, Test Acc {test_accuracy[-1]:.4f}")

elapsed = time.time() - start_time  # End timer
print(f"Training completed in {elapsed:.2f} seconds")

training_curve_plot(
    title          = "CNN on MNIST – ReLU activation - ADAM optimization",
    train_costs    = train_costs,
    test_costs     = test_costs,
    train_accuracy = train_accuracy,
    test_accuracy  = test_accuracy,
    batch_size     = batch_size,
    learning_rate  = learning_rate,
    num_epochs     = num_epochs,
    elapsed        = elapsed
)

# Optional: save the figure
plt.savefig("cnn_mnist_learning_curves_ADAM.png", dpi=150, bbox_inches="tight")

"""Layer-by-layer (weights + biases):

Conv1: (1 × 3 × 3 × 8) + 8 = 72 + 8 = 80
Conv2: (8 × 3 × 3 × 16) + 16 = 1 152 + 16 = 1 168
Conv3: (16 × 3 × 3 × 32) + 32 = 4 608 + 32 = 4 640
FC: (32 × 7 × 7 × 10) + 10 = 15 680 + 10 = 15 690

Total trainable parameters: 21 578

Comparison to the previous Fully connected network (784→128→64→10):
For a linear layer (fully-connected) from in_features to out_features:

Weights: A matrix of size in_features × out_features = in_features * out_features parameters.
Biases: A vector of size out_features = out_features parameters.
Total per layer: Weights + biases.

Our network has three linear layers (activations like ReLU don't add parameters):

Layer 1: 784 (input) → 128 (hidden1)
Weights: 784 * 128 = 100,352
Biases: 128
Subtotal: 100,480

Layer 2: 128 → 64 (hidden2)
Weights: 128 * 64 = 8,192
Biases: 64
Subtotal: 8,256

Layer 3: 64 → 10 (output)
Weights: 64 * 10 = 640
Biases: 10
Subtotal: 650


Grand total trainable parameters: 100,480 + 8,256 + 650 = 109,386

Total params ≈ 109 322 (roughly 5× more than this CNN)
CNN has far fewer parameters because convolutions reuse the same kernel weights across all spatial positions (weight sharing). The parameter count depends only on kernel size + input/output channels (not on 28×28 spatial size — as the hint says). This is why CNNs are more efficient and generalize better on images.

**EXERCISE -- 4**
"""

X_train, Y_train, X_test, Y_test = load_mnist()
X_train_cnn = X_train.reshape(-1, 1, 28, 28)
X_test_cnn = X_test.reshape(-1, 1, 28, 28)

train_dataset = TensorDataset(torch.tensor(X_train_cnn, dtype=torch.float32),
                              torch.tensor(np.argmax(Y_train, axis=1), dtype=torch.long))
test_dataset = TensorDataset(torch.tensor(X_test_cnn, dtype=torch.float32),
                             torch.tensor(np.argmax(Y_test, axis=1), dtype=torch.long))

batch_size = 128
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

#@title Plain Deeper CNN (Without Residuals – to Show Degradation)

class PlainDeepCNN(nn.Module):
    def __init__(self):
        super().__init__()
        # Initial conv (to 8 channels)
        self.conv_init = nn.Conv2d(1, 8, kernel_size=3, stride=1, padding=1)

        # Layer 1: extra conv for depth (8→8)
        self.conv1_extra = nn.Conv2d(8, 8, kernel_size=3, stride=1, padding=1)

        # Downsample to 16
        self.conv2 = nn.Conv2d(8, 16, kernel_size=3, stride=2, padding=1)
        self.conv2_extra = nn.Conv2d(16, 16, kernel_size=3, stride=1, padding=1)

        # Downsample to 32
        self.conv3 = nn.Conv2d(16, 32, kernel_size=3, stride=2, padding=1)
        self.conv3_extra = nn.Conv2d(32, 32, kernel_size=3, stride=1, padding=1)

        # FC
        self.fc = nn.Linear(32 * 7 * 7, 10)

    def forward(self, x):
        x = F.relu(self.conv_init(x))

        # Layer 1 (8 ch)
        x = F.relu(self.conv1_extra(x))

        # Layer 2 (16 ch)
        x = F.relu(self.conv2(x))
        x = F.relu(self.conv2_extra(x))

        # Layer 3 (32 ch)
        x = F.relu(self.conv3(x))
        x = F.relu(self.conv3_extra(x))

        x = x.view(x.size(0), -1)
        x = self.fc(x)
        return x

# Instantiate
model_plain_deep = PlainDeepCNN().to(device)

#@title Residual CNN (With Skip Connections)

class ResidualBlock(nn.Module):
    def __init__(self, in_channels, out_channels, stride=1):
        super().__init__()
        self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size=3, stride=stride, padding=1, bias=False)
        self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size=3, stride=1, padding=1, bias=False)

        self.skip = nn.Sequential()
        if stride != 1 or in_channels != out_channels:
            self.skip = nn.Conv2d(in_channels, out_channels, kernel_size=1, stride=stride, bias=False)

    def forward(self, x):
        out = F.relu(self.conv1(x))
        out = self.conv2(out)
        out += self.skip(x)  # Skip connection
        out = F.relu(out)
        return out

class ResidualCNN(nn.Module):
    def __init__(self):
        super().__init__()
        # Initial conv to 8
        self.conv_init = nn.Conv2d(1, 8, kernel_size=3, stride=1, padding=1)

        # Layer 1: residual block (8→8, stride=1)
        self.layer1 = ResidualBlock(8, 8, stride=1)

        # Downsample to 16 (stride=2 in block)
        self.layer2 = ResidualBlock(8, 16, stride=2)

        # Downsample to 32
        self.layer3 = ResidualBlock(16, 32, stride=2)

        # FC
        self.fc = nn.Linear(32 * 7 * 7, 10)

    def forward(self, x):
        x = F.relu(self.conv_init(x))

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)

        x = x.view(x.size(0), -1)
        x = self.fc(x)
        return x

# Instantiate
model_res = ResidualCNN().to(device)

#@title Deeper Residual CNN (Add Extra Blocks for Depth)

class DeeperResidualCNN(nn.Module):
    def __init__(self):
        super().__init__()
        # Initial to 8
        self.conv_init = nn.Conv2d(1, 8, kernel_size=3, stride=1, padding=1)

        # Layer 1: two residual blocks (8→8)
        self.layer1_block1 = ResidualBlock(8, 8, stride=1)
        self.layer1_block2 = ResidualBlock(8, 8, stride=1)

        # Down to 16
        self.layer2_block1 = ResidualBlock(8, 16, stride=2)
        self.layer2_block2 = ResidualBlock(16, 16, stride=1)

        # Down to 32
        self.layer3_block1 = ResidualBlock(16, 32, stride=2)
        self.layer3_block2 = ResidualBlock(32, 32, stride=1)

        # FC
        self.fc = nn.Linear(32 * 7 * 7, 10)

    def forward(self, x):
        x = F.relu(self.conv_init(x))

        # Layer 1
        x = self.layer1_block1(x)
        x = self.layer1_block2(x)

        # Layer 2
        x = self.layer2_block1(x)
        x = self.layer2_block2(x)

        # Layer 3
        x = self.layer3_block1(x)
        x = self.layer3_block2(x)

        x = x.view(x.size(0), -1)
        x = self.fc(x)
        return x

# Instantiate
model_deep_res = DeeperResidualCNN().to(device)

#@title Training Function (Reusable for All Models)

def train_model(model, optimizer, criterion, train_loader, test_loader, num_epochs=50):
    train_costs = []
    test_costs = []
    train_accuracy = []
    test_accuracy = []

    start_time = time.time()

    for epoch in range(num_epochs):
        model.train()
        batch_losses = []
        batch_accs = []

        for batch_x, batch_y in train_loader:
            batch_x, batch_y = batch_x.to(device), batch_y.to(device)
            optimizer.zero_grad()
            outputs = model(batch_x)
            loss = criterion(outputs, batch_y)
            loss.backward()
            optimizer.step()

            batch_losses.append(loss.item())
            _, preds = torch.max(outputs, 1)
            acc = (preds == batch_y).float().mean().item()
            batch_accs.append(acc)

        train_costs.append(np.mean(batch_losses))
        train_accuracy.append(np.mean(batch_accs))

        model.eval()
        test_loss = 0
        test_correct = 0
        with torch.no_grad():
            for test_x, test_y in test_loader:
                test_x, test_y = test_x.to(device), test_y.to(device)
                outputs = model(test_x)
                loss = criterion(outputs, test_y)
                test_loss += loss.item() * test_x.size(0)
                _, preds = torch.max(outputs, 1)
                test_correct += (preds == test_y).sum().item()

        test_costs.append(test_loss / len(test_loader.dataset))
        test_accuracy.append(test_correct / len(test_loader.dataset))

        print(f"Epoch {epoch+1}/{num_epochs}: Train Cost {train_costs[-1]:.4f}, Train Acc {train_accuracy[-1]:.4f}, Test Cost {test_costs[-1]:.4f}, Test Acc {test_accuracy[-1]:.4f}")

    elapsed = time.time() - start_time
    print(f"Training completed in {elapsed:.2f} seconds")

    return train_costs, test_costs, train_accuracy, test_accuracy, elapsed

#@title Train and Plot Plain Deeper Model

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model_plain_deep.parameters(), lr=0.01)  # Adam from Exercise 3

train_costs, test_costs, train_acc, test_acc, elapsed = train_model(
    model_plain_deep, optimizer, criterion, train_loader, test_loader, num_epochs=50
)

training_curve_plot(
    title="Plain Deeper CNN (No Residuals)",
    train_costs=train_costs,
    test_costs=test_costs,
    train_accuracy=train_acc,
    test_accuracy=test_acc,
    batch_size=batch_size,
    learning_rate=0.01,
    num_epochs=50,
    elapsed=elapsed
)

#@title Train and Plot Residual Model (Shallow)

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model_res.parameters(), lr=0.01)

train_costs, test_costs, train_acc, test_acc, elapsed = train_model(
    model_res, optimizer, criterion, train_loader, test_loader, num_epochs=50
)

training_curve_plot(
    title="CNN with Residual Connections (Shallow)",
    train_costs=train_costs,
    test_costs=test_costs,
    train_accuracy=train_acc,
    test_accuracy=test_acc,
    batch_size=batch_size,
    learning_rate=0.01,
    num_epochs=50,
    elapsed=elapsed
)

#@title Train and Plot Deeper Residual Model

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model_deep_res.parameters(), lr=0.01)

train_costs, test_costs, train_acc, test_acc, elapsed = train_model(
    model_deep_res, optimizer, criterion, train_loader, test_loader, num_epochs=50
)

training_curve_plot(
    title="Deeper CNN with Residual Connections",
    train_costs=train_costs,
    test_costs=test_costs,
    train_accuracy=train_acc,
    test_accuracy=test_acc,
    batch_size=batch_size,
    learning_rate=0.01,
    num_epochs=50,
    elapsed=elapsed
)

#@title Residual Block with BN/Dropout Options

class ResidualBlock(nn.Module):
    def __init__(self, in_channels, out_channels, stride=1, use_bn=False, dropout_p=0.0):
        super().__init__()
        self.use_bn = use_bn
        self.dropout_p = dropout_p

        self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size=3, stride=stride, padding=1, bias=not use_bn)
        self.bn1 = nn.BatchNorm2d(out_channels) if use_bn else nn.Identity()
        self.dropout1 = nn.Dropout(dropout_p) if dropout_p > 0 else nn.Identity()

        self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size=3, stride=1, padding=1, bias=not use_bn)
        self.bn2 = nn.BatchNorm2d(out_channels) if use_bn else nn.Identity()
        self.dropout2 = nn.Dropout(dropout_p) if dropout_p > 0 else nn.Identity()

        self.skip = nn.Sequential()
        if stride != 1 or in_channels != out_channels:
            self.skip = nn.Sequential(
                nn.Conv2d(in_channels, out_channels, kernel_size=1, stride=stride, bias=not use_bn),
                nn.BatchNorm2d(out_channels) if use_bn else nn.Identity()
            )

    def forward(self, x):
        out = self.conv1(x)
        out = self.bn1(out)
        out = F.relu(out)
        out = self.dropout1(out)

        out = self.conv2(out)
        out = self.bn2(out)
        out = self.dropout2(out)

        out += self.skip(x)
        out = F.relu(out)
        return out

#@title Residual CNN with BN or Dropout

class RegularizedResidualCNN(nn.Module):
    def __init__(self, use_bn=False, dropout_p=0.0):
        super().__init__()
        # Initial conv to 8
        self.conv_init = nn.Conv2d(1, 8, kernel_size=3, stride=1, padding=1, bias=not use_bn)
        self.bn_init = nn.BatchNorm2d(8) if use_bn else nn.Identity()

        # Layer 1: 8→8, stride=1
        self.layer1 = ResidualBlock(8, 8, stride=1, use_bn=use_bn, dropout_p=dropout_p)

        # Layer 2: 8→16, stride=2
        self.layer2 = ResidualBlock(8, 16, stride=2, use_bn=use_bn, dropout_p=dropout_p)

        # Layer 3: 16→32, stride=2
        self.layer3 = ResidualBlock(16, 32, stride=2, use_bn=use_bn, dropout_p=dropout_p)

        # FC with optional dropout
        self.dropout_fc = nn.Dropout(dropout_p) if dropout_p > 0 else nn.Identity()
        self.fc = nn.Linear(32 * 7 * 7, 10)

    def forward(self, x):
        x = self.conv_init(x)
        x = self.bn_init(x)
        x = F.relu(x)

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)

        x = x.view(x.size(0), -1)
        x = self.dropout_fc(x)
        x = self.fc(x)
        return x

# BN variant
model_bn = RegularizedResidualCNN(use_bn=True, dropout_p=0.0).to(device)
# Dropout variant
model_dropout = RegularizedResidualCNN(use_bn=False, dropout_p=0.5).to(device)

#@title Train BN Variant

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model_bn.parameters(), lr=0.01)  # Higher lr OK with BN

train_costs, test_costs, train_acc, test_acc, elapsed = train_model(
    model_bn, optimizer, criterion, train_loader, test_loader, num_epochs=50
)

training_curve_plot(
    title="Residual CNN with Batch Normalization",
    train_costs=train_costs,
    test_costs=test_costs,
    train_accuracy=train_acc,
    test_accuracy=test_acc,
    batch_size=batch_size,
    learning_rate=0.01,
    num_epochs=50,
    elapsed=elapsed
)

#@title Train Dropout Variant

criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model_dropout.parameters(), lr=0.01)

train_costs, test_costs, train_acc, test_acc, elapsed = train_model(
    model_dropout, optimizer, criterion, train_loader, test_loader, num_epochs=50
)

training_curve_plot(
    title="Residual CNN with Dropout (p=0.5)",
    train_costs=train_costs,
    test_costs=test_costs,
    train_accuracy=train_acc,
    test_accuracy=test_acc,
    batch_size=batch_size,
    learning_rate=0.01,
    num_epochs=50,
    elapsed=elapsed
)

def plot_confusion_matrix(y_labels, y_preds):
    class_names = np.arange(10)  # MNIST labels 0-9
    cm = confusion_matrix(y_labels, y_preds).astype(np.float64)

    plt.figure(figsize=(6, 6))
    plt.imshow(cm, interpolation='nearest', cmap='coolwarm')
    plt.title("Confusion Matrix")
    plt.colorbar(shrink=0.75, fraction=0.05)

    tick_marks = np.arange(len(class_names))
    plt.xticks(tick_marks, class_names)
    plt.yticks(tick_marks, class_names)
    plt.xlabel("Predicted label")
    plt.ylabel("True label")

    plt.tight_layout()
    plt.show()

#@title Confusion Matrix and Misclassifications for Best Model

# Assume model_bn is best; change to model_dropout if not
best_model = model_dropout  # model_bn or

best_model.eval()
all_preds = []
all_labels = []
all_images = []

with torch.no_grad():
    for images, labels in test_loader:
        images, labels = images.to(device), labels.to(device)
        outputs = best_model(images)
        preds = torch.argmax(outputs, dim=1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())
        all_images.extend(images.cpu().numpy())

# Confusion matrix
plot_confusion_matrix(all_labels, all_preds)

# Misclassifications: Find 10 wrong ones (try one per class)
misclassified = np.where(np.array(all_preds) != np.array(all_labels))[0]
unique_classes = []
selected = []

for idx in misclassified:
    true_label = all_labels[idx]
    if true_label not in unique_classes:
        unique_classes.append(true_label)
        selected.append(idx)
    if len(selected) == 10:
        break

# Plot 10 misclassified images
fig, axs = plt.subplots(2, 5, figsize=(10, 5))
axs = axs.ravel()

for i, idx in enumerate(selected):
    img = all_images[idx].squeeze()
    true = all_labels[idx]
    pred = all_preds[idx]
    axs[i].imshow(img, cmap='gray')
    axs[i].set_title(f"True: {true}, Pred: {pred}")
    axs[i].axis('off')

plt.tight_layout()
plt.show()