# -*- coding: utf-8 -*-
"""DL_hand-in 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N39hRSO9HxHVway9DoAaNQbQ6VGMp7Xr

This script implements all exercises:
1. Fully-connected ReLU net in PyTorch (comparison to Assignment 1)
2. Exact convolutional network spec
3. Adam optimizer
4. Residual connections (plain deeper vs residual variants)
5. Regularization (BatchNorm + Dropout variants) + confusion matrix & misclassifications

"""

import time
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

# Import utilities from utils.py (must be uploaded)
from utils import load_mnist, training_curve_plot

# =============================================================================
# Global Settings
# =============================================================================
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

batch_size = 128
num_epochs = 50

# Load and prepare MNIST data once
X_train, Y_train, X_test, Y_test = load_mnist()

# FC version (flattened)
train_dataset_fc = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                                 torch.tensor(np.argmax(Y_train, axis=1), dtype=torch.long))
test_dataset_fc  = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                                 torch.tensor(np.argmax(Y_test, axis=1), dtype=torch.long))

train_loader_fc = DataLoader(train_dataset_fc, batch_size=batch_size, shuffle=True)
test_loader_fc  = DataLoader(test_dataset_fc, batch_size=batch_size, shuffle=False)

# CNN version (reshaped [N,1,28,28])
X_train_cnn = X_train.reshape(-1, 1, 28, 28)
X_test_cnn  = X_test.reshape(-1, 1, 28, 28)

train_dataset_cnn = TensorDataset(torch.tensor(X_train_cnn, dtype=torch.float32),
                                  torch.tensor(np.argmax(Y_train, axis=1), dtype=torch.long))
test_dataset_cnn  = TensorDataset(torch.tensor(X_test_cnn, dtype=torch.float32),
                                  torch.tensor(np.argmax(Y_test, axis=1), dtype=torch.long))

train_loader_cnn = DataLoader(train_dataset_cnn, batch_size=batch_size, shuffle=True)
test_loader_cnn  = DataLoader(test_dataset_cnn, batch_size=batch_size, shuffle=False)

criterion = nn.CrossEntropyLoss()

# =============================================================================
# Utility: Print model parameters
# =============================================================================
def print_model_parameters(model):
    """Print layer-wise and total trainable parameters."""
    print("Layer-by-layer trainable parameter counts:\n")
    total = 0
    for name, param in model.named_parameters():
        if param.requires_grad:
            count = param.numel()
            print(f"{name:25s}: {count:8,} parameters")
            total += count
    print(f"\nTotal trainable parameters: {total:,}")
    return total

# =============================================================================
# Reusable training function (used for all exercises)
# =============================================================================
def train_model(model, optimizer, train_loader, test_loader, title, epochs=50):
    """Train model and return lists for plotting + elapsed time."""
    train_costs, test_costs = [], []
    train_accs, test_accs = [], []

    start = time.time()

    for epoch in range(epochs):
        model.train()
        batch_losses, batch_accs = [], []

        for x, y in train_loader:
            x, y = x.to(device), y.to(device)
            optimizer.zero_grad()
            out = model(x)
            loss = criterion(out, y)
            loss.backward()
            optimizer.step()

            batch_losses.append(loss.item())
            pred = out.argmax(dim=1)
            acc = (pred == y).float().mean().item()
            batch_accs.append(acc)

        train_costs.append(np.mean(batch_losses))
        train_accs.append(np.mean(batch_accs))

        model.eval()
        test_loss_sum, test_correct, n = 0.0, 0, 0
        with torch.no_grad():
            for x, y in test_loader:
                x, y = x.to(device), y.to(device)
                out = model(x)
                loss = criterion(out, y)
                test_loss_sum += loss.item() * x.size(0)
                pred = out.argmax(dim=1)
                test_correct += (pred == y).sum().item()
                n += y.size(0)

        test_costs.append(test_loss_sum / n)
        test_accs.append(test_correct / n)

        print(f"Epoch {epoch+1}/{epochs}: Train {train_costs[-1]:.4f} / {train_accs[-1]:.4f} | "
              f"Test {test_costs[-1]:.4f} / {test_accs[-1]:.4f}")

    elapsed = time.time() - start
    print(f"{title} completed in {elapsed:.1f} sec")

    training_curve_plot(
        title=title,
        train_costs=train_costs,
        test_costs=test_costs,
        train_accuracy=train_accs,
        test_accuracy=test_accs,
        batch_size=batch_size,
        learning_rate=optimizer.param_groups[0]['lr'],
        num_epochs=epochs,
        elapsed=elapsed
    )

    return train_costs, test_costs, train_accs, test_accs, elapsed

# =============================================================================
# Exercise 1: Fully-Connected ReLU Network (PyTorch)
# =============================================================================
class FCNet(nn.Module):
    """Multi-layer FC network matching Assignment 1: [784, 128, 64, 10] with ReLU."""
    def __init__(self):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(784, 128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.ReLU(),
            nn.Linear(64, 10)
        )

    def forward(self, x):
        return self.net(x)

print("Exercise 1: FC ReLU Network")
model_fc = FCNet().to(device)
print_model_parameters(model_fc)  # Should be ~109,386 params

# Train with three learning rates
lrs = [0.01, 0.005, 0.003]
for lr in lrs:
    optimizer = optim.SGD(model_fc.parameters(), lr=lr)
    train_model(model_fc, optimizer, train_loader_fc, test_loader_fc,
                title=f"FC Net with ReLU (lr={lr})", epochs=num_epochs)

# =============================================================================
# Exercise 2: Exact Convolutional Network
# =============================================================================
class ExactMNISTCNN(nn.Module):
    """Exact CNN as specified in Exercise 2."""
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 8, kernel_size=3, stride=1, padding=1)
        self.conv2 = nn.Conv2d(8, 16, kernel_size=3, stride=1, padding=1)
        self.conv3 = nn.Conv2d(16, 32, kernel_size=3, stride=1, padding=1)
        self.fc    = nn.Linear(32 * 7 * 7, 10)

    def forward(self, x):
        x = F.relu(self.conv1(x))
        x = F.max_pool2d(x, kernel_size=2, stride=2)
        x = F.relu(self.conv2(x))
        x = F.max_pool2d(x, kernel_size=2, stride=2)
        x = F.relu(self.conv3(x))
        x = x.view(x.size(0), -1)
        x = self.fc(x)
        return x

print("\nExercise 2: Exact CNN")
model_cnn = ExactMNISTCNN().to(device)
print_model_parameters(model_cnn)  # Should be 21,578 params

# Train (lr=0.01 as recommended)
optimizer = optim.SGD(model_cnn.parameters(), lr=0.01)
train_model(model_cnn, optimizer, train_loader_cnn, test_loader_cnn,
            title="CNN on MNIST – ReLU activation", epochs=num_epochs)

# =============================================================================
# Exercise 3: ADAM optimizer
# =============================================================================
print("\nExercise 3: Adam Optimizer")
optimizer_adam = optim.Adam(model_cnn.parameters(), lr=0.01)  # Used 0.01 as per your run
train_model(model_cnn, optimizer_adam, train_loader_cnn, test_loader_cnn,
            title="CNN on MNIST – ReLU activation - ADAM optimization", epochs=num_epochs)

# =============================================================================
# Exercise 4: Residual Connections
# =============================================================================
class ResidualBlock(nn.Module):
    """Basic residual block with two 3x3 convs + skip connection."""
    def __init__(self, in_ch, out_ch, stride=1):
        super().__init__()
        self.conv1 = nn.Conv2d(in_ch, out_ch, 3, stride=stride, padding=1, bias=False)
        self.conv2 = nn.Conv2d(out_ch, out_ch, 3, stride=1, padding=1, bias=False)
        self.skip = nn.Sequential()
        if stride != 1 or in_ch != out_ch:
            self.skip = nn.Conv2d(in_ch, out_ch, 1, stride=stride, bias=False)

    def forward(self, x):
        out = F.relu(self.conv1(x))
        out = self.conv2(out)
        out += self.skip(x)
        return F.relu(out)

# Plain deeper (no skip)
class PlainDeepCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.init = nn.Conv2d(1, 8, 3, 1, 1)
        self.l1 = nn.Conv2d(8, 8, 3, 1, 1)
        self.l2 = nn.Conv2d(8, 16, 3, 2, 1)
        self.l2e = nn.Conv2d(16, 16, 3, 1, 1)
        self.l3 = nn.Conv2d(16, 32, 3, 2, 1)
        self.l3e = nn.Conv2d(32, 32, 3, 1, 1)
        self.fc = nn.Linear(32*7*7, 10)

    def forward(self, x):
        x = F.relu(self.init(x))
        x = F.relu(self.l1(x))
        x = F.relu(self.l2(x))
        x = F.relu(self.l2e(x))
        x = F.relu(self.l3(x))
        x = F.relu(self.l3e(x))
        x = x.view(x.size(0), -1)
        return self.fc(x)

# Shallow residual
class ShallowResidualCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.init = nn.Conv2d(1, 8, 3, 1, 1)
        self.l1 = ResidualBlock(8, 8, 1)
        self.l2 = ResidualBlock(8, 16, 2)
        self.l3 = ResidualBlock(16, 32, 2)
        self.fc = nn.Linear(32*7*7, 10)

    def forward(self, x):
        x = F.relu(self.init(x))
        x = self.l1(x)
        x = self.l2(x)
        x = self.l3(x)
        x = x.view(x.size(0), -1)
        return self.fc(x)

# Deeper residual
class DeeperResidualCNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.init = nn.Conv2d(1, 8, 3, 1, 1)
        self.l1_1 = ResidualBlock(8, 8, 1)
        self.l1_2 = ResidualBlock(8, 8, 1)
        self.l2_1 = ResidualBlock(8, 16, 2)
        self.l2_2 = ResidualBlock(16, 16, 1)
        self.l3_1 = ResidualBlock(16, 32, 2)
        self.l3_2 = ResidualBlock(32, 32, 1)
        self.fc = nn.Linear(32*7*7, 10)

    def forward(self, x):
        x = F.relu(self.init(x))
        x = self.l1_1(x)
        x = self.l1_2(x)
        x = self.l2_1(x)
        x = self.l2_2(x)
        x = self.l3_1(x)
        x = self.l3_2(x)
        x = x.view(x.size(0), -1)
        return self.fc(x)

print("\nExercise 4: Residual Connections")
model_plain_deep = PlainDeepCNN().to(device)
model_shallow_res = ShallowResidualCNN().to(device)
model_deep_res = DeeperResidualCNN().to(device)

for name, m in [("Plain Deeper", model_plain_deep),
                ("Shallow Residual", model_shallow_res),
                ("Deeper Residual", model_deep_res)]:
    print(f"\n{name}:")
    print_model_parameters(m)
    optimizer = optim.Adam(m.parameters(), lr=0.01)
    train_model(m, optimizer, train_loader_cnn, test_loader_cnn,
                title=f"{name} CNN", epochs=num_epochs)

# =============================================================================
# Exercise 5: Regularization (BN & Dropout)
# =============================================================================
class RegularizedResidualCNN(nn.Module):
    """Residual CNN with optional BN or Dropout."""
    def __init__(self, use_bn=False, dropout_p=0.0):
        super().__init__()
        self.init = nn.Conv2d(1, 8, 3, 1, 1, bias=not use_bn)
        self.bn_init = nn.BatchNorm2d(8) if use_bn else nn.Identity()

        self.l1 = ResidualBlock(8, 8, 1, use_bn, dropout_p)
        self.l2 = ResidualBlock(8, 16, 2, use_bn, dropout_p)
        self.l3 = ResidualBlock(16, 32, 2, use_bn, dropout_p)

        self.dropout_fc = nn.Dropout(dropout_p) if dropout_p > 0 else nn.Identity()
        self.fc = nn.Linear(32*7*7, 10)

    def forward(self, x):
        x = self.init(x)
        x = self.bn_init(x)
        x = F.relu(x)
        x = self.l1(x)
        x = self.l2(x)
        x = self.l3(x)
        x = x.view(x.size(0), -1)
        x = self.dropout_fc(x)
        return self.fc(x)

print("\nExercise 5: Regularization")
model_bn = RegularizedResidualCNN(use_bn=True, dropout_p=0.0).to(device)
model_dropout = RegularizedResidualCNN(use_bn=False, dropout_p=0.5).to(device)

for name, m in [("Batch Normalization", model_bn), ("Dropout p=0.5", model_dropout)]:
    print(f"\n{name}:")
    print_model_parameters(m)
    optimizer = optim.Adam(m.parameters(), lr=0.01)
    train_model(m, optimizer, train_loader_cnn, test_loader_cnn,
                title=f"Residual CNN with {name}", epochs=num_epochs)

# Confusion matrix & misclassifications (use BN as best)
best_model = model_bn
best_model.eval()
all_preds, all_labels, all_images = [], [], []

with torch.no_grad():
    for images, labels in test_loader_cnn:
        images, labels = images.to(device), labels.to(device)
        out = best_model(images)
        preds = out.argmax(dim=1)
        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(labels.cpu().numpy())
        all_images.extend(images.cpu().numpy())

# Plot confusion matrix
plot_confusion_matrix(all_labels, all_preds)

# Misclassifications: 10 examples (one per class if possible)
mis_idx = np.where(np.array(all_preds) != np.array(all_labels))[0]
seen = set()
selected = []

for idx in mis_idx:
    true = all_labels[idx]
    if true not in seen:
        seen.add(true)
        selected.append(idx)
    if len(selected) == 10:
        break

fig, axs = plt.subplots(2, 5, figsize=(12, 5))
axs = axs.ravel()
for i, idx in enumerate(selected):
    img = all_images[idx].squeeze()
    true, pred = all_labels[idx], all_preds[idx]
    axs[i].imshow(img, cmap='gray')
    axs[i].set_title(f"True: {true}, Pred: {pred}")
    axs[i].axis('off')
plt.tight_layout()
plt.show()